export const availableFilters = [
  { name: "isEmail", label: "Email", type: "validator" },
  { name: "isNumeric", label: "Только цифры", type: "validator" },
  { name: "isCyrillic", label: "Кириллица", type: "validator" },
  {
    name: "isDate",
    label: "Дата (YYYY-MM-DD или DD.MM.YYYY)",
    type: "validator",
  },
  { name: "isURL", label: "URL", type: "validator" },
  { name: "isPhone", label: "Телефон", type: "validator" },
  { name: "isLatin", label: "Латиница", type: "validator" },
  { name: "isAlphanumeric", label: "Буквы + цифры", type: "validator" },
  { name: "isEmpty", label: "Пустая строка", type: "validator" },
  { name: "isJSON", label: "JSON", type: "validator" },
  { name: "isUUID", label: "UUID", type: "validator" },
  { name: "isStrongPassword", label: "Сильный пароль", type: "validator" },

  { name: "replaceFirst8With7", label: "8 → 7", type: "action" },
  { name: "cleanSpaces", label: "Убрать лишние пробелы", type: "action" },
  { name: "toLowerCase", label: "В нижний регистр", type: "action" },
  { name: "toUpperCase", label: "В верхний регистр", type: "action" },
  { name: "removeSpecialChars", label: "Убрать спецсимволы", type: "action" },
  { name: "removeDigits", label: "Убрать цифры", type: "action" },
  { name: "removeLetters", label: "Убрать буквы", type: "action" },
  { name: "onlyDigits", label: "Оставить только цифры", type: "action" },
  { name: "onlyLetters", label: "Оставить только буквы", type: "action" },
  { name: "normalizePhone", label: "Нормализовать телефон", type: "action" },
  { name: "trimStart", label: "Обрезать пробелы слева", type: "action" },
  { name: "trimEnd", label: "Обрезать пробелы справа", type: "action" },
  { name: "capitalize", label: "Первая буква заглавная", type: "action" },
  { name: "titleCase", label: "Каждое слово с заглавной", type: "action" },
  { name: "maskEmail", label: "Скрыть часть email", type: "action" },
  { name: "maskPhone", label: "Скрыть часть телефона", type: "action" },
];
